import {chromium}from'playwright';import fs from'node:fs/promises';import path from'node:path';
const root=path.resolve(import.meta.dirname,'..'),arg=process.argv.find(x=>x.startsWith('--iteration=')),iteration=arg?+arg.split('=')[1]:1,dir=root+'/public/process';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'/home/dev/.local/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader','--use-angle=swiftshader','--disable-gpu-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1060},deviceScaleFactor:1});page.setDefaultTimeout(90000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto('http://127.0.0.1:4187/?test=1',{waitUntil:'networkidle',timeout:120000});await page.waitForFunction(()=>window.__catStudio?.ready||window.__catError,null,{timeout:180000});if(await page.evaluate(()=>window.__catError))throw Error(await page.evaluate(()=>window.__catError));await page.waitForTimeout(1800);
const tag=String(iteration).padStart(2,'0');for(const v of['three','front','right','back','left']){await page.evaluate(v=>window.__catStudio.setView(v),v);await page.waitForTimeout(550);await page.screenshot({path:`${dir}/iteration-${tag}-${v}.png`,clip:await page.locator('#stage').boundingBox(),timeout:90000});console.log('Captured '+v);}
await page.evaluate(()=>window.__catStudio.setView('three'));await page.screenshot({path:`${dir}/iteration-${tag}-desktop.png`});const stats=await page.evaluate(()=>window.__catStudio.stats());
const checks=[];checks.push({test:'WebGL scene loads',pass:stats.triangles>10000});for(const v of['front','left','right','back']){await page.locator(`[data-view=${v}]`).click();checks.push({test:`${v} camera button`,pass:await page.evaluate(v=>window.__catStudio.stats().view===v,v)});}
await page.locator('#fur').uncheck();checks.push({test:'Fur toggle',pass:await page.evaluate(()=>!window.__catStudio.cat.furGroup.visible)});await page.locator('#fur').check();await page.locator('#wire').check();checks.push({test:'Mesh inspection',pass:await page.evaluate(()=>window.__catStudio.cat.body.material.wireframe)});await page.locator('#wire').uncheck();await page.locator('#reference-toggle').click();checks.push({test:'Reference comparison dialog',pass:await page.locator('#reference-dialog').evaluate(d=>d.open)});await page.locator('#close-ref').click();
if(process.argv.includes('--export')){await fs.mkdir(root+'/public/downloads',{recursive:true});const pending=page.waitForEvent('download',{timeout:180000});await page.locator('#export').click();const download=await pending;const output=root+'/public/downloads/GPT6-Astra-Pro_ColabDev_ThreeJS_BWCat.glb';await download.saveAs(output);const f=await fs.open(output,'r'),header=Buffer.alloc(4);await f.read(header,0,4,0);await f.close();const st=await fs.stat(output);checks.push({test:'Binary glTF export via download button',pass:st.size>1000&&header.toString()==='glTF'});console.log('GLB bytes '+st.size);}
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.__catStudio.setView('three'));await page.waitForTimeout(500);await page.screenshot({path:`${dir}/iteration-${tag}-mobile.png`});checks.push({test:'Mobile has no horizontal overflow',pass:await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)});checks.push({test:'No browser exceptions',pass:errors.length===0});
const report={iteration,time:new Date().toISOString(),stats,checks,errors};await fs.writeFile(root+`/public/process/test-${tag}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();if(checks.some(x=>!x.pass))process.exitCode=1;
